language: erlang

sudo: required

env:

#
  - GS_VERSION=3.2.10  TEST=Seaside3
#  - GS_VERSION=3.2.10  TEST=Seaside3Upgrade GS_OLD_VERSION=3.1.0.6

before_script:
  - export PROJECT_HOME="$(pwd)"
  - git clone https://github.com/GsDevKit/GsDevKit_home.git
  - cd GsDevKit_home
  - export GS_HOME="$(pwd)"
  - export PATH=$GS_HOME/bin:$PATH
  - export GS_TRAVIS=true
  - cd etc
  - ln -s $PROJECT_HOME .
  - echo $GS_HOME
  - echo $PROJECT_HOME
  - ls $PROJECT_HOME
  - ls $GS_HOME
  - ls $GS_HOME/etc


script:
  - $GS_HOME/etc/GsDevKit_seaside/tests/testTravisCI.sh
